---
name:  ⭐ Feature request
description: Suggest an idea.
labels: [enhancement]
body:
  - type: dropdown
    id: desire
    attributes:
      label: Desire
      description: How much do you want this feature?
      options:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 10
    validations:
      required: true
  - type: checkboxes
    id: help
    attributes:
      label: Help
      description: How much are you willing to help?. Its okay if you choose none.
      options:
        - label: Discuss
        - label: Test
        - label: Code
  - type: textarea
    attributes:
      label: Description
    validations:
      required: true
